[workspace]
resolver = "2"
members = ["day*"]

[workspace.dependencies]
divan = "0.1.16"
indoc = "2.0.5"
itertools = "0.13.0"
miette = "7.4.0"
nom = "7.1.3"
rayon = "1.10.0"
thiserror = "2.0.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
